module.exports = {
  PORT: process.env.PORT || 3000,
  MONGODB_URI: process.env.MONGODB_URI,
  JWT_SECRET: process.env.JWT_SECRET,

  // ORIGINS ALLOWED BY CORS (COMMA SEPARATED). EMPTY = ALLOW ALL
  CORS_ORIGIN: process.env.CORS_ORIGIN || "",

  // EMAIL THAT RECEIVES CONTACT FORM NOTIFICATIONS (FALLBACK: COMPANY EMAIL IN SETTINGS)
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || "",

  // ALLOW CREATING THE FIRST ADMIN USER WHEN THE DATABASE HAS NO USERS
  ALLOW_BOOTSTRAP_ADMIN: process.env.ALLOW_BOOTSTRAP_ADMIN === "true",

  // CLOUDINARY (IMAGE UPLOADS FROM THE ADMIN PANEL)
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME || "",
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY || "",
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET || "",
  CLOUDINARY_FOLDER: process.env.CLOUDINARY_FOLDER || "alupvcbarcelona",

  // PUBLIC WEBSITE URL (USED IN EMAILS)
  SITE_URL: process.env.SITE_URL || "https://alupvcbarcelona.es",
};
